export const APP_LOADING_START  = 'APP_LOADING_START';
export const APP_LOADING_END    = 'APP_LOADING_END';
export const APP_LOADING_TOGGLE = 'APP_LOADING_TOGGLE';

export const NET_CONNECT_INIT  = 'NET_CONNECT_INIT';
export const NET_CONNECT_START = 'NET_CONNECT_START';
export const NET_CONNECT_END   = 'NET_CONNECT_END';
export const NET_CONNECT_ERROR = 'NET_CONNECT_ERROR';